create table person
(
    id            int primary key generated by default as identity,
    username      varchar(100) not null,
    year_of_birth int          not null,
    password      varchar      not null
);

insert into person (username, year_of_birth, password)
values ('user1', 1960, 'password1'),
       ('user2', 1960, 'password2');