version: '3.5'

services:
  spring_mvc-db:
    image: postgres
    container_name: first_security-db
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=first_security
    ports:
      - "5508:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data